//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVEntityProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCVENTITYEntities : DbContext
    {
        public DBCVENTITYEntities()
            : base("name=DBCVENTITYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLABILITIES> TBLABILITIES { get; set; }
        public virtual DbSet<TBLABOUTME> TBLABOUTME { get; set; }
        public virtual DbSet<TBLADDRESS> TBLADDRESS { get; set; }
        public virtual DbSet<TBLCONTACT> TBLCONTACT { get; set; }
        public virtual DbSet<TBLWORKS> TBLWORKS { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
    }
}
