//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVEntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCONTACT
    {
        public int ID { get; set; }
        public string FULLNAME { get; set; }
        public string EMAIL { get; set; }
        public string MESSAGE { get; set; }
        public string SUBJECT { get; set; }
    }
}
